#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate original geometry, unit normals and a Q7 sine table; no frame art."""
import argparse
import math
from pathlib import Path

VERTICES = [
    (0, 0, 44), (-5, 0, 18), (0, 6, 18), (5, 0, 18), (0, -4, 18),
    (-6, 0, -28), (0, 5, -28), (6, 0, -28), (0, -4, -28),
    (-42, 0, -24), (42, 0, -24),
    (-19, 0, -37), (19, 0, -37), (0, 0, -34),
    (0, 17, -28), (0, 4, -10),
    (-3, 4, 8), (0, 10, 8), (3, 4, 8), (0, 6, -6),
]
# Indices, outward hint, flags: bit 0 = two-sided sheet, bit 1 = dark canopy.
FACES = [
    ((0, 1, 2), (-1, 1, 1), 0), ((0, 2, 3), (1, 1, 1), 0),
    ((0, 3, 4), (1, -1, 1), 0), ((0, 4, 1), (-1, -1, 1), 0),
    ((1, 5, 6), (-1, 1, 0), 0), ((1, 6, 2), (-1, 1, 0), 0),
    ((2, 6, 7), (1, 1, 0), 0), ((2, 7, 3), (1, 1, 0), 0),
    ((3, 7, 8), (1, -1, 0), 0), ((3, 8, 4), (1, -1, 0), 0),
    ((4, 8, 5), (-1, -1, 0), 0), ((4, 5, 1), (-1, -1, 0), 0),
    ((5, 8, 6), (0, 0, -1), 0), ((6, 8, 7), (0, 0, -1), 0),
    ((1, 9, 5), (0, 1, 0), 1), ((3, 7, 10), (0, 1, 0), 1),
    ((5, 11, 13), (0, 1, 0), 1), ((7, 13, 12), (0, 1, 0), 1),
    ((6, 14, 15), (1, 0, 0), 1),
    ((2, 16, 17), (-1, 1, 1), 2), ((2, 17, 18), (1, 1, 1), 2),
    ((16, 19, 17), (-1, 1, -1), 2), ((17, 19, 18), (1, 1, -1), 2),
]

def mesh():
    result = []
    previous_normal = None
    for indices, hint, flags in FACES:
        a, b, c = (VERTICES[i] for i in indices)
        u, v = ([b[j] - a[j] for j in range(3)], [c[j] - a[j] for j in range(3)])
        n = [u[1]*v[2]-u[2]*v[1], u[2]*v[0]-u[0]*v[2], u[0]*v[1]-u[1]*v[0]]
        if sum(n[j]*hint[j] for j in range(3)) < 0:
            indices = (indices[0], indices[2], indices[1])
            n = [-x for x in n]
        length = math.sqrt(sum(x*x for x in n))
        normal = tuple(round(x*96/length) for x in n)
        key = (*normal, flags)
        # Bit 2 reuses the previous face's runtime culling/shade calculation.
        # Only identical normals with identical material flags may share it.
        stored_flags = flags | (4 if key == previous_normal else 0)
        result.append((*[i*3 for i in indices], *normal, stored_flags))
        previous_normal = key
    return result

def source():
    lines = ['; SPDX-License-Identifier: MIT', '; Generated by generate_model.py. Original mesh; no prerendered frames.',
             '.global vertices', '.global vertices_end', '.global faces', '.global faces_end', '.global sine',
             '.section .data, data', 'vertices:']
    lines += ['    .byte ' + ','.join(str(x & 255) for x in v) for v in VERTICES]
    lines += ['vertices_end:', 'faces:']
    lines += ['    .byte ' + ','.join(str(x & 255) for x in f) for f in mesh()]
    lines += ['faces_end:', 'sine:']
    s = [round(127*math.sin(i*math.tau/64)) & 255 for i in range(64)]
    lines += ['    .byte ' + ','.join(map(str, s[i:i+16])) for i in range(0,64,16)]
    return '\n'.join(lines) + '\n'

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    path = Path(__file__).with_name('model.s')
    if args.check:
        if path.read_text() != source():
            raise SystemExit('model.s is stale; run generate_model.py')
        print(f'Model verified: {len(VERTICES)} vertices, {len(FACES)} triangles')
    else:
        path.write_text(source())
