; SPDX-License-Identifier: MIT
; Generated by generate_model.py. Original mesh; no prerendered frames.
.global vertices
.global vertices_end
.global faces
.global faces_end
.global sine
.section .data, data
vertices:
    .byte 0,0,44
    .byte 251,0,18
    .byte 0,6,18
    .byte 5,0,18
    .byte 0,252,18
    .byte 250,0,228
    .byte 0,5,228
    .byte 6,0,228
    .byte 0,252,228
    .byte 214,0,232
    .byte 42,0,232
    .byte 237,0,219
    .byte 19,0,219
    .byte 0,0,222
    .byte 0,17,228
    .byte 0,4,246
    .byte 253,4,8
    .byte 0,10,8
    .byte 3,4,8
    .byte 0,6,250
vertices_end:
faces:
    .byte 0,6,3,183,61,14,0
    .byte 0,9,6,73,61,14,0
    .byte 0,12,9,60,182,11,0
    .byte 0,3,12,196,182,11,0
    .byte 3,18,15,195,74,1,0
    .byte 3,6,18,182,61,255,0
    .byte 6,21,18,61,74,254,0
    .byte 6,9,21,74,61,2,0
    .byte 9,24,21,53,176,1,0
    .byte 9,12,24,60,181,0,0
    .byte 12,15,24,203,176,0,0
    .byte 12,3,15,196,181,1,0
    .byte 15,18,24,0,0,160,0
    .byte 18,21,24,0,0,160,0
    .byte 3,15,27,0,96,0,1
    .byte 9,30,21,0,96,0,1
    .byte 15,39,33,0,96,0,1
    .byte 21,36,39,0,96,0,1
    .byte 18,42,45,96,0,0,1
    .byte 6,51,48,171,42,17,2
    .byte 6,54,51,85,42,17,2
    .byte 48,51,57,171,43,244,2
    .byte 51,54,57,85,43,244,2
faces_end:
sine:
    .byte 0,12,25,37,49,60,71,81,90,98,106,112,117,122,125,126
    .byte 127,126,125,122,117,112,106,98,90,81,71,60,49,37,25,12
    .byte 0,244,231,219,207,196,185,175,166,158,150,144,139,134,131,130
    .byte 129,130,131,134,139,144,150,158,166,175,185,196,207,219,231,244
