// SPDX-License-Identifier: MIT
import assert from 'node:assert/strict';
const sign=n=>n>=128?n-256:n;
const targets=[24,44,64,84,104];
const state=g=>({mode:g.read('penalty_mode'),power:g.read('penalty_power'),dir:sign(g.read('penalty_power_dir')),keeper:g.read('penalty_keeper'),kd:sign(g.read('penalty_keeper_dir')),target:g.read('penalty_target'),height:g.read('penalty_height'),progress:g.read('penalty_progress'),x:g.read('penalty_x'),y:g.read('penalty_y'),kicks:g.read('penalty_kicks'),goals:g.read('penalty_goals'),reason:g.read('penalty_reason'),count:g.read('penalty_count'),phase:g.read('phase')});
function world(before,stage){const s={...before};s.count=(s.count+1)&255;const patrol=()=>{s.keeper+=s.kd*(stage+2);if(s.keeper<16){s.keeper=16;s.kd=1;}if(s.keeper>104){s.keeper=104;s.kd=-1;}};if(s.mode===1){s.power+=s.dir;if(!s.power)s.dir=1;if(s.power===10)s.dir=-1;patrol();}else{++s.progress;if(s.progress<=4)patrol();else{s.keeper+=Math.sign(targets[s.target]-s.keeper)*Math.min(stage+1,Math.abs(targets[s.target]-s.keeper));}s.x=64+Math.floor((targets[s.target]-64)*s.progress/16);s.y=60+Math.floor(((s.height?14:24)-60)*s.progress/16);if(s.progress===16){const valid=s.height?s.power>=5&&s.power<=6:s.power>=4&&s.power<=7;s.reason=!valid?3:Math.abs(targets[s.target]-s.keeper)<=(s.height?5:8)?2:1;if(s.reason===1)s.goals++;s.kicks++;s.mode=3;if(s.kicks===10)s.phase=s.goals>=6+stage?4:5;}}return s;}
export async function checkPenalty(g){
 await g.start();let ticks=0,second=false,third=false;const frame=g.frame.bind(g);g.frame=()=>{const before=state(g),panel=frame(),after=state(g);if(before.phase===2&&after.count!==before.count){let expected=world(before,g.read('stage'));expected.target=after.target;expected.height=after.height;assert.deepEqual(after,expected,'Charge, keeper patrol/dive, flight interpolation and ten-kick scoring match the independent model');ticks++;}return panel;};
 const idle=state(g);for(let n=0;n<20;n++){const blink=g.read('cursor_blink_mask');g.frame();if(blink===g.read('cursor_blink_mask'))assert.equal(g.word('dirty_bytes'),0);}assert.deepEqual(state(g),idle);await g.save('gameplay-1');g.tap('space');for(let n=0;n<8;n++)g.frame();g.tap('return');const paused=state(g);for(let n=0;n<24;n++){g.frame();assert.equal(g.word('dirty_bytes'),0);}assert.deepEqual(state(g),paused);g.tap('return');g.menu(1);assert.equal(g.read('penalty_mode'),0);assert.equal(g.read('penalty_kicks'),0);
 async function kick(wantGoal,stage,shot){if(g.read('penalty_mode')===3)g.tap('space');assert.equal(g.read('penalty_mode'),0);const desired=wantGoal==='save'?2:wantGoal?1:3;const target=wantGoal==='save'?2:wantGoal?(g.read('penalty_keeper')<64?4:0):2;while(g.read('penalty_target')!==target)g.tap(stage%2?'letter-d':'right');g.tap(shot%2?'up':'down');g.tap('space');let found=false;
  for(let n=0;n<700;n++){const s=state(g),guess={...s,mode:2};let predicted=guess;for(let i=0;i<16;i++)predicted=world(predicted,stage);if(desired===3?s.power===0:predicted.reason===desired){found=true;break;}g.frame();}
  assert.ok(found,'A visible timing window can beat the keeper');if(stage===1&&shot===2){await g.save('gameplay-2');second=true;}const locked=state(g);g.tap('space');assert.equal(g.read('penalty_mode'),2);assert.equal(g.read('penalty_power'),locked.power);let steps=0;while(g.read('penalty_mode')===2){g.frame();if(stage===2&&shot===3&&g.read('penalty_progress')===10&&!third){await g.save('gameplay-3');third=true;}assert.ok(++steps<120);}assert.equal(g.read('penalty_reason'),desired);}
 await kick('save',0,0);assert.equal(g.read('penalty_reason'),2);g.menu(2);g.hold('space',true);for(let n=0;n<10;n++)g.frame();assert.equal(g.read('penalty_mode'),1,'Held SPACE starts charging once without immediately releasing the kick');g.hold('space',false);g.frame();g.menu(1);
 for(let shot=0;shot<10;shot++)await kick(false,0,shot);assert.equal(g.read('phase'),5);g.tap('space');assert.equal(g.read('penalty_kicks'),0);
 for(let stage=0;stage<3;stage++){if(stage)g.tap('space');assert.equal(g.read('stage'),stage);for(let shot=0;shot<10;shot++)await kick(true,stage,shot);assert.equal(g.read('phase'),4,`Penalty challenge ${stage+1}`);assert.equal(g.read('penalty_goals'),10);}
 assert.ok(ticks>600&&second&&third);
}
