// SPDX-License-Identifier: MIT
import assert from 'node:assert/strict';
import {playPixelVisible} from './harness.mjs';
const signed=n=>n>=128?n-256:n;
const state=g=>({x:g.read('dock_x'),y:g.read('dock_y'),left:g.read('dock_left'),width:g.read('dock_width'),direction:signed(g.read('dock_direction')),speed:g.read('dock_speed'),mode:g.read('dock_mode'),count:g.read('dock_count'),goal:g.read('dock_goal'),flips:g.read('dock_flips'),score:g.word('dock_score'),landing:g.read('dock_landing_y'),ticks:g.read('dock_ticks'),judgement:g.read('dock_judgement'),phase:g.read('phase')});
export async function checkDock(g){
 await g.start();let worlds=0,second=false,third=false;const frame=g.frame.bind(g);
 function verifyPicture(s){const expected=new Uint8Array(1536);for(let x=0;x<128;x++)expected[7*192+x]=128;const span=(left,width,y,pattern)=>{assert.ok(left>=0&&left+width<=128&&y>=8&&y<=61&&y%2===0);const mask=3<<(y%8),top=1<<(y%8);for(let x=left;x<left+width;x++){const address=(y>>3)*192+x;expected[address]=(expected[address]&~mask)|((x+pattern)%4?mask:top);}};span(24,80,60,0);const lefts=g.read('dock_layers_left',20),widths=g.read('dock_layers_width',20);for(let n=0;n<s.count;n++)span(lefts[n],widths[n],58-2*n,n);if(s.mode!==3)span(s.x,s.width,s.y,s.count);const actual=g.machine.memory(g.symbols.framebuffer,1536);for(let band=1;band<8;band++)for(let x=0;x<128;x++)if(playPixelVisible(g,x,band*8))assert.equal(actual[band*192+x+g.read('view_origin')],expected[band*192+x],'Incremental stack equals reconstruction at '+x+', band '+band);}
 g.frame=()=>{const b=state(g),oldLeft=g.read('dock_layers_left',20),oldWidth=g.read('dock_layers_width',20),panel=frame(),after=state(g);if(b.phase===2&&after.ticks!==b.ticks){const s={...b,ticks:(b.ticks+1)&255};if(s.mode===1){s.x+=s.direction*s.speed;if(s.x<0){s.x=0;s.direction=1;}if(s.x>128-s.width){s.x=128-s.width;s.direction=-1;}}else{s.y=Math.min(s.landing,s.y+2);if(s.y===s.landing){const lo=Math.max(s.x,s.left),hi=Math.min(s.x+s.width,s.left+s.width),width=hi-lo;if(width<=0){s.phase=5;s.judgement=5;}else{s.judgement=width===s.width?3:4;s.score+=width+(s.judgement===3?20:0);s.left=lo;s.width=width;oldLeft[s.count]=lo;oldWidth[s.count]=width;s.count++;if(s.count===s.goal){s.phase=4;s.mode=3;}else{s.speed=Math.min(4,g.read('stage')+1+Math.floor(s.count/5));s.landing=58-2*s.count;s.y=s.landing-6;s.x=s.count%2?128-s.width:0;s.direction=s.count%2?-1:1;s.mode=1;}}}}assert.deepEqual(after,s,'Motion, intersections, score and height match the independent stack model');assert.deepEqual(g.read('dock_layers_left',20),oldLeft);assert.deepEqual(g.read('dock_layers_width',20),oldWidth);worlds++;}if([2,4,5].includes(after.phase))verifyPicture(after);return panel;};
 const idle=state(g);for(let n=0;n<20;n++){g.frame();assert.equal(g.word('dirty_bytes'),0);}assert.deepEqual(state(g),idle);g.tap('right');assert.equal(g.read('dock_x'),48);g.tap('left');assert.equal(g.read('dock_x'),0);g.menu(1);assert.equal(g.read('dock_flips'),3,'FLIP is unavailable before motion');g.tap('space');
 for(let n=0;n<4;n++){const before=state(g);g.menu(1);assert.equal(g.read('dock_flips'),Math.max(0,3-n-1));assert.equal(signed(g.read('dock_direction')),n<3?-before.direction:before.direction);}g.tap('return');const paused=state(g);for(let n=0;n<25;n++){g.frame();assert.equal(g.word('dirty_bytes'),0);}assert.deepEqual(state(g),paused);g.tap('return');g.menu(2);g.tap('space');
 let first=true;while(g.read('phase')===2){g.tap('space');assert.equal(g.read('dock_mode'),2);let n=0;while(g.read('dock_mode')===2&&g.read('phase')===2){g.frame();assert.ok(++n<25);}if(first){await g.save('gameplay-1');first=false;}}assert.equal(g.read('phase'),5);g.tap('space');
 g.tap('space');while(g.read('dock_x')!==g.read('dock_left'))g.frame();g.hold('space',true);g.frame();while(!g.read('dock_count'))g.frame();const count=g.read('dock_count');for(let n=0;n<40;n++)g.frame();assert.equal(g.read('dock_count'),count);assert.equal(g.read('dock_mode'),1);g.hold('space',false);g.frame();g.menu(2);
 for(let stage=0;stage<3;stage++){if(stage)g.tap('space');assert.equal(g.read('stage'),stage);assert.equal(g.read('dock_goal'),12+4*stage);g.tap('space');let guard=0;while(g.read('phase')===2){while(g.read('dock_x')!==g.read('dock_left')){g.frame();assert.ok(++guard<3000);}const before=state(g);g.hold('space',true);g.frame();assert.equal(g.read('dock_x'),before.x,'Drop locks the visible position before another movement step');g.hold('space',false);g.frame();while(g.read('dock_mode')===2)g.frame();assert.equal(g.read('dock_width'),80);if(stage===1&&g.read('dock_count')===8&&!second){await g.save('gameplay-2');second=true;}if(stage===2&&g.read('dock_count')===17&&!third){await g.save('gameplay-3');third=true;}}assert.equal(g.read('phase'),4);assert.equal(g.word('dock_score'),g.read('dock_goal')*100);}
 assert.ok(worlds>300&&second&&third);
}
